# Generated by Django 4.2 on 2023-09-28 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('names', models.CharField(default='Unknown Patient', max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('sex', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data_hs5s',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('IMC', models.FloatField()),
                ('body_fat', models.FloatField()),
                ('muscle', models.FloatField()),
                ('bone_salt_content', models.FloatField()),
                ('water', models.FloatField()),
                ('protein', models.FloatField()),
                ('visceral_fat_grade', models.FloatField()),
                ('basal_metabolism', models.FloatField()),
                ('physical_age', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Data_bp5s',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('sys', models.FloatField()),
                ('dia', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthApp.patient')),
            ],
        ),
    ]
