# Generated by Django 4.2 on 2023-09-29 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('name', models.CharField(choices=[('HS2S', 'Balance impédancemètre'), ('BP5S', 'Tensiomètre'), ('BG5S', 'Glucomètre'), ('PO3M', 'Oximètre de Pouls')], max_length=4, primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(default='Unknown Patient', max_length=200, unique=True)),
                ('age', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('gender', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data_hs5s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('IMC', models.FloatField()),
                ('body_fat', models.FloatField()),
                ('muscle', models.FloatField()),
                ('bone_salt_content', models.FloatField()),
                ('water', models.FloatField()),
                ('protein', models.FloatField()),
                ('visceral_fat_grade', models.FloatField()),
                ('basal_metabolism', models.FloatField()),
                ('physical_age', models.IntegerField()),
                ('measure_date', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Data_bp5s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys', models.FloatField()),
                ('dia', models.FloatField()),
                ('measure_date', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthApp.patient')),
            ],
        ),
    ]
