# Generated by Django 4.2 on 2023-09-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
