# Generated by Django 4.2 on 2023-09-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0002_rename_names_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
