# Generated by Django 4.2 on 2023-09-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0003_alter_patient_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data_hs5s',
            new_name='Data_hs2s',
        ),
    ]
